### ISSUE TITLE
database contention issues

### ISSUE THREAD

**Issue by nathanloyer** [onc-healthit/inferno#568]
**Subject of the issue**

So I've been trying to reproduce the issue documented [here](https://github.com/onc-healthit/inferno/issues/566) with a vanilla copy of inferno so it is more easily reproducible by anybody. In the process of doing this I uncovered [this other bug with docker-compose](https://github.com/onc-healthit/inferno/issues/567). I was able to produce another error just now that looks related to my original issue (#566), although the error message is not the same. My theory so far is that the ActiveRecord database framework you integrated with earlier this year to replace data mapper is not quite being used correctly when it comes to managing multiple requests in parallel.

**Your environment**
* Edition of inferno (Community or Program): **Community**
* Version of inferno: **main branch**
* Which browser and version(s) is the bug present on?: **Latest chrome as of 05/24/2021**

**Steps to reproduce**

I was able to produce this error consistently today. 

- check out the main branch in github
- update the `config.yml` to set the validators to the `internal` mode (since there's the bug #567)
- start up inferno with `docker-compose up`.
- Once everything is up and running, go to the inferno page in chrome in two different tabs. Do all the following steps in both tabs
- select the preset tests **Inferno Reference Server (US Core v3.1.1)**
- click **Begin**
- Next to **US Core v3.1.1 Profiles** click **Run All**
- In the pop up window, click **Execute**
- wait

Within a few minutes the server should die with the message **ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked**

**Expected behavior**

We should be able to run tests in parallel. We deploy inferno as a shared service that any one of a few dozen developers can call throughout the day to test their FHIR endpoints. We need to be able to handle at least a few dozen tests executions running in parallel.

**Actual behavior**

Server dies

```
inferno_1            | 172.21.0.1 - - [24/May/2021:21:12:20 +0000] "POST /inferno/iMAyZx2p5o/test_sets/ad_hoc_testing/sequence_result HTTP/1.1" 200 - 17.7825                                                                                                                                                                                                     [25/11578]
inferno_1            | bundler: failed to load command: rackup (/usr/local/bundle/bin/rackup)
inferno_1            | ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: INSERT INTO "inferno_models_test_results" ("id", "test_id", "name", "result", "required", "url", "description", "test_index", "created_at", "versions", "sequence_result_id") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
inferno_1            |   /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/statement.rb:108:in `step'
inferno_1            |   /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/statement.rb:108:in `block in each'
inferno_1            |   /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/statement.rb:107:in `loop'
inferno_1            |   /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/statement.rb:107:in `each'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:222:in `to_a'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:222:in `block (2 levels) in exec_query'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:213:in `block in exec_query'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:212:in `exec_query'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:130:in `exec_insert'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:162:in `insert'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/persistence.rb:187:in `_insert_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/persistence.rb:734:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/counter_cache.rb:184:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/locking/optimistic.rb:70:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/attribute_methods/dirty.rb:140:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/callbacks.rb:346:in `block in _create_record'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/callbacks.rb:346:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/timestamp.rb:102:in `_create_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/persistence.rb:705:in `create_or_update'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/callbacks.rb:342:in `block in create_or_update'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
inferno_1            |   /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/callbacks.rb:342:in `create_or_update'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/persistence.rb:275:in `save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/validations.rb:46:in `save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:310:in `block in save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:309:in `save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/suppressor.rb:44:in `save'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:377:in `insert_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:439:in `block (2 levels) in concat_records'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:458:in `replace_on_target'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:283:in `add_to_target'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:437:in `block in concat_records'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:435:in `each'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:435:in `concat_records'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/has_many_association.rb:117:in `concat_records'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:120:in `block in concat'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:135:in `block in transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:134:in `transaction'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_association.rb:120:in `concat'
inferno_1            |   /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/associations/collection_proxy.rb:1029:in `<<'
inferno_1            |   /var/www/inferno/lib/app/sequence_base.rb:209:in `block in run_tests'
inferno_1            |   /var/www/inferno/lib/app/sequence_base.rb:174:in `each'
inferno_1            |   /var/www/inferno/lib/app/sequence_base.rb:174:in `run_tests'
inferno_1            |   /var/www/inferno/lib/app/sequence_base.rb:125:in `start'
inferno_1            |   /var/www/inferno/lib/app/endpoint/test_set_endpoints.rb:182:in `block (3 levels) in included'
inferno_1            |   /usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:458:in `block (2 levels) in stream'
inferno_1            |   /usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:644:in `with_params'
inferno_1            |   /usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:458:in `block in stream'
inferno_1            |   /usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:424:in `block in each'
inferno_1            |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
inferno_inferno_1 exited with code 1
```

**Comment by Jammjammjamm** [comment]
This should be resolved by the 2.13.0 release. Please reopen this issue if it remains a problem.
